### post URL with JSON body
// @no-log
POST http://localhost:8080/api/shorten
Content-Type: application/json

{
  "url": "https://www.google.com"
}

### get URL list
// @no-log
GET http://localhost:8080/list

### get URL
// @no-log
GET http://localhost:8080/ac6bb669

### post URL 2
// @no-log
POST http://localhost:8080
Content-Type: text/plain

https://practicum.yandex.ru/

### post URL 1
// @no-log
POST http://localhost:8080
Content-Type: text/plain

https://www.yandex.ru/
